application: muitodoido-174815
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /static(.*)
  static_files: static\1
  upload: static.*


- url: .*
  script: core.main.app

